language: python
cache: pip

python:
    - "3.6"

install:
    - pip install jupyter
    
env:
  global:
  - USER="joy-rosie"
  - EMAIL="joytolia@hotmail.com"
  - REPO="probability"
  - REPO_DIR="probability_pages"
  - FILES="index.html"
  - GH_REPO="github.com/${USER}/${REPO}.git"

script:
  - jupyter nbconvert probability/probability_questions.ipynb --to html
  - mv -f probability/probability_questions.html index.html
  - git clone git://${GH_REPO} ${REPO_DIR}
  - mv -f ${FILES} ${REPO_DIR}
  - cd ${REPO_DIR}
  - git remote
  - git config user.email ${EMAIL}
  - git config user.name ${USER}
  - git add ${FILES}
  - git diff --quiet && git diff --staged --quiet || git commit -m "update probability index.html"
  - git push "https://${GITHUB_API_KEY}@${GH_REPO}" master
